#!/usr/bin/env python3
"""Publish pipeline blog posts to the PatchBook Jekyll site as reports.

Usage:
    python publish_to_patchbook.py              # publish all reports
    python publish_to_patchbook.py CVE-2024-30088   # publish one CVE
    python publish_to_patchbook.py --commit         # also git commit in patchbook/
"""
import re
import sys
import subprocess
from datetime import datetime, timezone
from pathlib import Path

WORKSPACE = Path(__file__).parent
BLOGS_DIR = WORKSPACE / "data" / "blogs"
REPORTS_DIR = WORKSPACE / "patchbook" / "_reports"

# Pipeline-generated header prefix to strip before publishing
_HEADER_RE = re.compile(
    r"^# CVE-[\w-]+\s*\n\s*\*Generated by kernel-cve-pipeline\*\s*\n\s*---\s*\n",
    re.MULTILINE,
)
_CVE_RE    = re.compile(r"^(CVE-\d{4}-\d+)", re.IGNORECASE)
_TITLE_RE  = re.compile(r"^# (.+)$", re.MULTILINE)
_CVSS_RE   = re.compile(r"CVSS[^0-9]*([\d]+\.[0-9])")
# Patch (Patch Tuesday) date the pipeline stamps into the metadata box. The report's
# published date is keyed off this — the date the fix shipped, not when we wrote the report.
_PATCHDATE_RE = re.compile(r"\*\*Patch date:\*\*\s*(\d{4}-\d{2}-\d{2})")
_TS_RE     = re.compile(r"_(\d{8}T\d{6})$")  # stem suffix like _20260610T205532
# Machine-readable block the blog generator emits at the very top of the post:
#   <!--meta
#   title: ...
#   excerpt: ...
#   -->
_META_RE   = re.compile(r"<!--\s*meta\s*\n(.*?)\n\s*-->", re.DOTALL | re.IGNORECASE)


def _parse_meta_block(text: str) -> dict:
    """Parse the `<!--meta ... -->` block if present. Returns {} when absent."""
    m = _META_RE.search(text)
    if not m:
        return {}
    out: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip().lower()
        if key in ("title", "excerpt") and val.strip():
            out[key] = val.strip()
    return out


def _extract_meta(text: str, stem: str) -> dict:
    cve_id = ""
    m = _CVE_RE.match(stem)
    if m:
        cve_id = m.group(1).upper()

    # strip the pipeline header before looking for title
    body = _HEADER_RE.sub("", text, count=1).lstrip()

    # Prefer the explicit metadata block the generator emits; fall back to scraping.
    meta = _parse_meta_block(text)

    title = meta.get("title", "")
    if not title:
        for m in _TITLE_RE.finditer(body):
            candidate = m.group(1).strip()
            # skip bare "CVE-XXXX-NNNNN" headings (pipeline artifact)
            if not re.fullmatch(r"CVE-[\w-]+", candidate, re.IGNORECASE):
                title = candidate
                break

    # Scan for the CVSS score with the <!--meta--> block removed. It sits between
    # the header and the bullet list that carries the score, and leaving it in
    # pushed "CVSS" past the 600-character window entirely — every post was
    # published with no cvss frontmatter, so the severity badge never rendered.
    cvss = ""
    m = _CVSS_RE.search(_META_RE.sub("", body, count=1).lstrip()[:600])
    if m:
        cvss = m.group(1)

    excerpt = meta.get("excerpt", "")
    if not excerpt:
        # first paragraph longer than 60 chars that isn't a heading or code block
        for para in body.split("\n\n"):
            stripped = para.strip()
            if stripped.startswith("#") or stripped.startswith("```") or stripped.startswith("|"):
                continue
            # skip the "**CVE-XXXX** | CVSS ... | binary" metadata line
            if stripped.startswith("**CVE-") and "|" in stripped:
                continue
            if stripped == "---" or len(stripped) < 60:
                continue
            excerpt = stripped
            break
    excerpt = excerpt[:300]

    m = _PATCHDATE_RE.search(body)
    patch_date = m.group(1) if m else ""

    return {"cve_id": cve_id, "title": title, "cvss": cvss, "excerpt": excerpt,
            "patch_date": patch_date}


def _existing_block(dest: Path, key: str) -> list[str]:
    """Return a named frontmatter block from an already-published report.

    Used for `editors:` — the credits readers add to themselves in the pull
    request that changes a report (see patchbook/_layouts/report.html). Those are
    human contributions that the pipeline knows nothing about, so re-running
    publish must not wipe them; we carry the existing block forward verbatim.
    Returns the block lines (`<key>:` and its indented items) or [].

    Votes are deliberately *not* handled here: they live in the vote database
    behind patchbook/worker/, never in frontmatter.
    """
    if not dest.exists():
        return []
    lines = dest.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return []
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return []
    fm = lines[1:end]
    start = next((i for i, l in enumerate(fm) if l.strip() == f"{key}:"), None)
    if start is None:
        return []
    block = [fm[start]]
    for l in fm[start + 1:]:
        # indented list items / mapping entries belong to the block
        if l[:1] in (" ", "\t") or l.strip().startswith("-"):
            block.append(l)
        else:
            break
    return block


def _report_date(path: Path) -> datetime:
    """Derive date from filename timestamp or file mtime."""
    m = _TS_RE.search(path.stem)
    if m:
        try:
            return datetime.strptime(m.group(1), "%Y%m%dT%H%M%S").replace(tzinfo=timezone.utc)
        except ValueError:
            pass
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)


def _select_reports(filter_cve: str | None) -> list[Path]:
    """Return one canonical .md per CVE (prefer base, skip timestamped & .prompt.txt)."""
    if not BLOGS_DIR.exists():
        print(f"[!] Blogs directory not found: {BLOGS_DIR}")
        return []

    # group files by CVE id
    groups: dict[str, list[Path]] = {}
    for f in sorted(BLOGS_DIR.glob("*.md")):
        m = _CVE_RE.match(f.stem)
        if not m:
            continue
        cve = m.group(1).upper()
        if filter_cve and cve != filter_cve.upper():
            continue
        groups.setdefault(cve, []).append(f)

    selected = []
    for cve, files in groups.items():
        # Publish the newest generation for each CVE. Regenerating a report writes a
        # fresh timestamped file (save_blog_post only reuses the bare name for the
        # very first run), so the latest regeneration must win — otherwise publish
        # would keep re-selecting the stale original base file. Tie-break on the
        # bare (timestamp-less) name so a lone first-run file still selects.
        newest = max(files, key=lambda f: (_report_date(f), bool(_TS_RE.search(f.stem))))
        selected.append(newest)

    return selected


def _slug(path: Path) -> str:
    """Extract the descriptive slug from the filename (part after CVE-YYYY-NNNNN_)."""
    stem = path.stem
    stem = _TS_RE.sub("", stem)  # remove timestamp suffix
    parts = stem.split("_", 1)
    return parts[1] if len(parts) > 1 else stem


def publish(filter_cve: str | None = None, do_commit: bool = False) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    reports = _select_reports(filter_cve)

    if not reports:
        print("[!] No matching reports found.")
        return

    published = []
    for src in reports:
        text = src.read_text(encoding="utf-8")
        meta = _extract_meta(text, src.stem)
        # Prefer the patch (Patch Tuesday) date from the report over the file's
        # generation date, so the site's dates/graph reflect when the fix shipped.
        date_str = meta.get("patch_date") or _report_date(src).strftime("%Y-%m-%d")

        if not meta["title"]:
            print(f"[!] Could not extract title from {src.name}, skipping.")
            continue

        # strip the pipeline header and the machine-readable meta block; keep the rest
        body = _HEADER_RE.sub("", text, count=1)
        body = _META_RE.sub("", body, count=1).lstrip()

        frontmatter_lines = [
            "---",
            f"layout: report",
            f'title: "{meta["title"].replace(chr(34), chr(39))}"',
            f"date: {date_str}",
        ]
        if meta["cve_id"]:
            frontmatter_lines.append(f"cve_id: {meta['cve_id']}")
        if meta["cvss"]:
            frontmatter_lines.append(f"cvss: {meta['cvss']}")
        if meta["excerpt"]:
            safe_excerpt = meta["excerpt"].replace('"', "'").replace("\n", " ")
            frontmatter_lines.append(f'excerpt: "{safe_excerpt}"')

        cve_lower = meta["cve_id"].lower() if meta["cve_id"] else ""
        dest_name = f"{date_str}-{cve_lower}-{_slug(src)}.md"
        dest = REPORTS_DIR / dest_name

        # carry forward editor credits merged via PR since the last publish
        frontmatter_lines.extend(_existing_block(dest, "editors"))

        frontmatter_lines.append("---")
        frontmatter_lines.append("")
        dest.write_text("\n".join(frontmatter_lines) + body, encoding="utf-8")
        print(f"[+] {src.name}  →  patchbook/_reports/{dest_name}")
        published.append(meta["cve_id"] or src.stem)

    if not published:
        return

    print(f"\n[*] Published {len(published)} report(s).")

    if do_commit:
        patchbook_dir = WORKSPACE / "patchbook"
        cve_list = ", ".join(published)
        try:
            subprocess.run(
                ["git", "-C", str(patchbook_dir), "add", "-A"],
                check=True,
            )
            subprocess.run(
                ["git", "-C", str(patchbook_dir), "commit", "-m", f"publish: {cve_list}"],
                check=True,
            )
            print(f"[+] Committed to patchbook: {cve_list}")
        except subprocess.CalledProcessError as e:
            print(f"[!] Git commit failed: {e}")
    else:
        print("[*] Run with --commit to also git commit in patchbook/.")


if __name__ == "__main__":
    args = sys.argv[1:]
    do_commit = "--commit" in args
    args = [a for a in args if a != "--commit"]
    filter_cve = args[0] if args else None
    publish(filter_cve=filter_cve, do_commit=do_commit)
