#!/usr/bin/env python3
"""Publish pipeline blog posts to the PatchBook Jekyll site.

Usage:
    python publish_to_patchbook.py              # publish all posts
    python publish_to_patchbook.py CVE-2024-30088   # publish one CVE
    python publish_to_patchbook.py --commit         # also git commit in patchbook/
"""
import re
import sys
import subprocess
from datetime import datetime, timezone
from pathlib import Path

WORKSPACE = Path(__file__).parent
BLOGS_DIR = WORKSPACE / "data" / "blogs"
POSTS_DIR = WORKSPACE / "patchbook" / "_posts"

# Pipeline-generated header prefix to strip before publishing
_HEADER_RE = re.compile(
    r"^# CVE-[\w-]+\s*\n\s*\*Generated by kernel-cve-pipeline\*\s*\n\s*---\s*\n",
    re.MULTILINE,
)
_CVE_RE    = re.compile(r"^(CVE-\d{4}-\d+)", re.IGNORECASE)
_TITLE_RE  = re.compile(r"^# (.+)$", re.MULTILINE)
_CVSS_RE   = re.compile(r"CVSS[^0-9]*([\d]+\.[0-9])")
_TS_RE     = re.compile(r"_(\d{8}T\d{6})$")  # stem suffix like _20260610T205532


def _extract_meta(text: str, stem: str) -> dict:
    cve_id = ""
    m = _CVE_RE.match(stem)
    if m:
        cve_id = m.group(1).upper()

    # strip the pipeline header before looking for title
    body = _HEADER_RE.sub("", text, count=1).lstrip()

    title = ""
    for m in _TITLE_RE.finditer(body):
        candidate = m.group(1).strip()
        # skip bare "CVE-XXXX-NNNNN" headings (pipeline artifact)
        if not re.fullmatch(r"CVE-[\w-]+", candidate, re.IGNORECASE):
            title = candidate
            break

    cvss = ""
    m = _CVSS_RE.search(body[:600])
    if m:
        cvss = m.group(1)

    # excerpt: first paragraph longer than 60 chars that isn't a heading or code block
    excerpt = ""
    for para in body.split("\n\n"):
        stripped = para.strip()
        if stripped.startswith("#") or stripped.startswith("```") or stripped.startswith("|"):
            continue
        # skip the "**CVE-XXXX** | CVSS ... | binary" metadata line
        if stripped.startswith("**CVE-") and "|" in stripped:
            continue
        if stripped == "---" or len(stripped) < 60:
            continue
        excerpt = stripped[:240]
        break

    return {"cve_id": cve_id, "title": title, "cvss": cvss, "excerpt": excerpt}


def _existing_validations(dest: Path) -> list[str]:
    """Return the `validations:` frontmatter block from an already-published post.

    Community validation marks (added by the GitHub Action, see
    patchbook/scripts/apply_validation.py) live in the post frontmatter. Re-running
    publish must not wipe them, so we carry the existing block forward verbatim.
    Returns the block lines (`validations:` and its indented items) or [].
    """
    if not dest.exists():
        return []
    lines = dest.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return []
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return []
    fm = lines[1:end]
    start = next((i for i, l in enumerate(fm) if l.strip() == "validations:"), None)
    if start is None:
        return []
    block = [fm[start]]
    for l in fm[start + 1:]:
        # indented list items / mapping entries belong to the block
        if l[:1] in (" ", "\t") or l.strip().startswith("-"):
            block.append(l)
        else:
            break
    return block


def _post_date(path: Path) -> datetime:
    """Derive date from filename timestamp or file mtime."""
    m = _TS_RE.search(path.stem)
    if m:
        try:
            return datetime.strptime(m.group(1), "%Y%m%dT%H%M%S").replace(tzinfo=timezone.utc)
        except ValueError:
            pass
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)


def _select_posts(filter_cve: str | None) -> list[Path]:
    """Return one canonical .md per CVE (prefer base, skip timestamped & .prompt.txt)."""
    if not BLOGS_DIR.exists():
        print(f"[!] Blogs directory not found: {BLOGS_DIR}")
        return []

    # group files by CVE id
    groups: dict[str, list[Path]] = {}
    for f in sorted(BLOGS_DIR.glob("*.md")):
        m = _CVE_RE.match(f.stem)
        if not m:
            continue
        cve = m.group(1).upper()
        if filter_cve and cve != filter_cve.upper():
            continue
        groups.setdefault(cve, []).append(f)

    selected = []
    for cve, files in groups.items():
        # prefer file whose stem has no timestamp suffix
        base = [f for f in files if not _TS_RE.search(f.stem)]
        selected.append(base[0] if base else files[0])

    return selected


def _slug(path: Path) -> str:
    """Extract the descriptive slug from the filename (part after CVE-YYYY-NNNNN_)."""
    stem = path.stem
    stem = _TS_RE.sub("", stem)  # remove timestamp suffix
    parts = stem.split("_", 1)
    return parts[1] if len(parts) > 1 else stem


def publish(filter_cve: str | None = None, do_commit: bool = False) -> None:
    POSTS_DIR.mkdir(parents=True, exist_ok=True)
    posts = _select_posts(filter_cve)

    if not posts:
        print("[!] No matching posts found.")
        return

    published = []
    for src in posts:
        text = src.read_text(encoding="utf-8")
        meta = _extract_meta(text, src.stem)
        date = _post_date(src)

        if not meta["title"]:
            print(f"[!] Could not extract title from {src.name}, skipping.")
            continue

        # strip the pipeline header; keep everything after it
        body = _HEADER_RE.sub("", text, count=1).lstrip()

        frontmatter_lines = [
            "---",
            f"layout: post",
            f'title: "{meta["title"].replace(chr(34), chr(39))}"',
            f"date: {date.strftime('%Y-%m-%d')}",
        ]
        if meta["cve_id"]:
            frontmatter_lines.append(f"cve_id: {meta['cve_id']}")
        if meta["cvss"]:
            frontmatter_lines.append(f"cvss: {meta['cvss']}")
        if meta["excerpt"]:
            safe_excerpt = meta["excerpt"].replace('"', "'").replace("\n", " ")
            frontmatter_lines.append(f'excerpt: "{safe_excerpt}"')

        cve_lower = meta["cve_id"].lower() if meta["cve_id"] else ""
        dest_name = f"{date.strftime('%Y-%m-%d')}-{cve_lower}-{_slug(src)}.md"
        dest = POSTS_DIR / dest_name

        # carry forward community validation marks from a prior publish
        frontmatter_lines.extend(_existing_validations(dest))

        frontmatter_lines.append("---")
        frontmatter_lines.append("")
        dest.write_text("\n".join(frontmatter_lines) + body, encoding="utf-8")
        print(f"[+] {src.name}  →  patchbook/_posts/{dest_name}")
        published.append(meta["cve_id"] or src.stem)

    if not published:
        return

    print(f"\n[*] Published {len(published)} post(s).")

    if do_commit:
        patchbook_dir = WORKSPACE / "patchbook"
        cve_list = ", ".join(published)
        try:
            subprocess.run(
                ["git", "-C", str(patchbook_dir), "add", "-A"],
                check=True,
            )
            subprocess.run(
                ["git", "-C", str(patchbook_dir), "commit", "-m", f"publish: {cve_list}"],
                check=True,
            )
            print(f"[+] Committed to patchbook: {cve_list}")
        except subprocess.CalledProcessError as e:
            print(f"[!] Git commit failed: {e}")
    else:
        print("[*] Run with --commit to also git commit in patchbook/.")


if __name__ == "__main__":
    args = sys.argv[1:]
    do_commit = "--commit" in args
    args = [a for a in args if a != "--commit"]
    filter_cve = args[0] if args else None
    publish(filter_cve=filter_cve, do_commit=do_commit)
